<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <Folder Include="Shell\" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Tests\**\*.cs" />
        <Compile Remove="src\**\*.cs" />
        <AvaloniaResource Remove="src\**\*.axaml" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="src\Asharia.Studio.Application\Asharia.Studio.Application.csproj" />
      <ProjectReference Include="src\Asharia.Studio.DevelopmentHost\Asharia.Studio.DevelopmentHost.csproj"
                        Condition="'$(Configuration)' == 'Debug'" />
      <ProjectReference Include="src\Asharia.Studio.DevelopmentProtocol\Asharia.Studio.DevelopmentProtocol.csproj"
                        Condition="'$(Configuration)' == 'Debug'" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.4" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    </ItemGroup>

</Project>
