"""Render deterministic CMake and C++ bytes for one fixed Host Template."""

from __future__ import annotations


HOST_TEMPLATE_CMAKE_PATH = "asharia-host-template.cmake"
HOST_TEMPLATE_MAIN_PATH = "src/main.cpp"
HOST_TEMPLATE_SUBSYSTEM = "console"
HOST_TEMPLATE_RUNTIME_OUTPUT_DIRECTORY = "asharia-host/bin/$<CONFIG>"
HOST_TEMPLATE_FILE_DESCRIPTORS = (
    (HOST_TEMPLATE_CMAKE_PATH, "cmake-host-template", "text/x-cmake"),
    (HOST_TEMPLATE_MAIN_PATH, "registration-verification-main", "text/x-c++src"),
)

_UTF8_BOM = b"\xef\xbb\xbf"


def render_registration_verification_main() -> bytes:
    """Render the revision-2 entry point backed by the frozen callback table."""

    text = r'''#include <cstdio>
#include <string_view>
#include <utility>

#if defined(_WIN32)
#include <fcntl.h>
#include <io.h>
#endif

#include "asharia/generated/static_composition_root.hpp"
#include "asharia/host_runtime/static_factory_callback_table.hpp"
#include "asharia/host_runtime/static_factory_registration_snapshot_json.hpp"

namespace {

    constexpr std::string_view kVerificationArgument{"--asharia-verify-static-registration"};

    int fail(const char* code, int exitCode) noexcept {
        std::fputs(code, stderr);
        std::fputc('\n', stderr);
        return exitCode;
    }

} // namespace

int main(int argc, char** argv) noexcept {
    if (argc != 2 || argv == nullptr || argv[1] == nullptr ||
        std::string_view{argv[1]} != kVerificationArgument) {
        return fail("host-verification.invalid-arguments", 64);
    }

    auto recorder = asharia::host_runtime::createStaticFactoryRegistrationRecorder(
        asharia::generated::staticFactoryRegistrationCapacity());
    if (!recorder) {
        return fail("host-verification.recorder-create-failed", 70);
    }

    asharia::generated::recordStaticFactoryProviders(*recorder);
    auto table = std::move(*recorder).finish();
    if (!table) {
        return fail("host-verification.registration-failed", 71);
    }

    const auto& snapshot = table->registrationSnapshot();
    auto rendered = asharia::host_runtime::renderStaticFactoryRegistrationSnapshotJson(snapshot);
    if (!rendered) {
        return fail("host-verification.snapshot-render-failed", 72);
    }

#if defined(_WIN32)
    // Canonical handoff bytes use LF even when the Windows CRT defaults to text mode.
    if (_setmode(_fileno(stdout), _O_BINARY) == -1) {
        return fail("host-verification.stdout-mode-failed", 73);
    }
#endif

    if (std::fwrite(rendered->data(), 1, rendered->size(), stdout) != rendered->size() ||
        std::fflush(stdout) != 0) {
        return fail("host-verification.stdout-write-failed", 74);
    }
    return 0;
}
'''
    return _UTF8_BOM + text.encode("utf-8")
def render_windows_development_cmake(
    target_name: str,
    template_generation_id: str,
    static_composition_generation_id: str,
) -> bytes:
    """Render the CMake adapter that owns the final executable target."""

    lines = [
        "# Generated by tools/host_executable_template.py. Do not edit.",
        "if(NOT WIN32)",
        '  message(FATAL_ERROR "windows-development-v1 requires Windows")',
        "endif()",
        "if(NOT DEFINED ASHARIA_STATIC_COMPOSITION_ROOT)",
        '  message(FATAL_ERROR "ASHARIA_STATIC_COMPOSITION_ROOT must be explicit")',
        "endif()",
        "if(NOT COMMAND asharia_configure_target)",
        '  message(FATAL_ERROR "asharia_configure_target must exist before the Host Template")',
        "endif()",
        f"if(TARGET {target_name})",
        f'  message(FATAL_ERROR "Host target \'{target_name}\' already exists")',
        "endif()",
        "get_filename_component(_asharia_static_composition_root",
        '    "${ASHARIA_STATIC_COMPOSITION_ROOT}" ABSOLUTE)',
        'include("${_asharia_static_composition_root}/asharia-static-composition.cmake")',
        f"add_executable({target_name}",
        '    "${CMAKE_CURRENT_LIST_DIR}/src/main.cpp")',
        f"asharia_configure_target({target_name})",
        f"set_target_properties({target_name} PROPERTIES",
        "    WIN32_EXECUTABLE FALSE",
        f'    OUTPUT_NAME "{target_name}"',
        '    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/asharia-host/bin/$<CONFIG>"',
        f'    ASHARIA_HOST_TEMPLATE_GENERATION_ID "{template_generation_id}"',
        ")",
        f"asharia_attach_static_composition({target_name})",
        f"get_target_property(_asharia_attached_generation {target_name}",
        "    ASHARIA_STATIC_COMPOSITION_GENERATION_ID)",
        f'if(NOT _asharia_attached_generation STREQUAL "{static_composition_generation_id}")',
        '  message(FATAL_ERROR "Host Template static-composition generation mismatch")',
        "endif()",
        "",
    ]
    return "\n".join(lines).encode("utf-8")
